In [2]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.datasets import make_classification

In [3]:
if torch.cuda.is_available():
    print("GPU available")
    print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available")

GPU available
Using GPU : NVIDIA GeForce RTX 4060 Laptop GPU


In [4]:
# Step 1: Create a synthetic classification dataset using sklearn
x, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [5]:
x=torch.tensor(x,dtype=torch.float64)
y=torch.tensor(y,dtype=torch.float64)

In [6]:
from torch.utils.data import DataLoader,Dataset

In [7]:
class ProcessData(Dataset):
    def __init__(self,features,labels):
        self.features = features
        self.labels = labels
    
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index],self.labels[index]
        return super().__getitem__(index)

In [8]:
dataset = ProcessData(x,y)

In [9]:
dataset[1]

(tensor([-1.1402, -0.8388], dtype=torch.float64),
 tensor(0., dtype=torch.float64))

In [10]:
dl=DataLoader(dataset,batch_size=2,shuffle=False)

In [11]:
for batch_feature,batch_labels in dl:
    print(batch_feature)
    print(batch_labels)
    print('-'*50)

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]], dtype=torch.float64)
tensor([1., 0.], dtype=torch.float64)
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]], dtype=torch.float64)
tensor([0., 0.], dtype=torch.float64)
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]], dtype=torch.float64)
tensor([0., 1.], dtype=torch.float64)
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]], dtype=torch.float64)
tensor([1., 1.], dtype=torch.float64)
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]], dtype=torch.float64)
tensor([1., 0.], dtype=torch.float64)
--------------------------------------------------


In [12]:
class MysimpleNN(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid
    
    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out